### ISSUE TITLE
Code base linking (CBL) to provision AVS?

### ISSUE THREAD

**Issue by robertoimai** [espressif/esp-avs-sdk#22]
Is it possible to do CBL instead of companion app when provisioning avs?
I'm trying to figure out the best way to provision thousands of devices when manufacturing.
Our devices need to ship with avs already provisioned and everyone of them will be linked to our own amazon account, since this is going to be our product we want to have control over which skills are enabled on the product. We will possibly be using Alexa for Business.

**Comment by avsheth** [comment]
Hi @robertoimai ,
CBL is not yet supported in the SDK.
I guess for your usecase, you can use nvs partition generator utility, as suggested in #20 for flashing avs tokens on multiple devices.

I believe WiFi creds won't be fixed at the time of manufacturing, so may be you can create a csv with just refreshToken and clientID parameters and flash the corresponding binary at 0x9000. And for WiFi provisioning you can use Espressif's provisioning app APK rather than one  provided with esp-avs-sdk.

If you're looking to productize this, please check with Amazon if there's any limitation/complexities/issues with number of devices simultaneously operating with same Amazon account (couple of the things we observed is that when same query is asked to multiple devices simultaneously, it would send response to only one device and music playback cannot run on multiple devices simultaneously).

If you're looking to go to production, please contact us over email, so that we can help you better.
