### ISSUE TITLE
amazon music is not working  on ESP32-LyraTD-MSC

### ISSUE THREAD

**Issue by vijay-packetp** [espressif/esp-avs-sdk#33]
Hi All, 

I flashed the firmware lyratd_msc_sr on to  ESP32-LyraTD-MSC,  onboarding/ Provisioning went fine with esp-prov-v2.apk  android apk,  but when I ask to play amazon music , its saying "I cant play from Amazon music  on that device"   with my amazon account,  am able to play amazon music with my Amazon Echo Device.

are we missing anything to configure this development board? please let us know..

Thanks,
Kumar

**Comment by avsheth** [comment]
Hi @vijaypacketp 
In order to access Amazon music, you'll have to get your clientID and clientSecret whitelisted from Amazon.
First party devices like Echo Dot and Echo already have whitelisted clientIDs and hence can directly access Amazon music. For third-party devices, this is required to be done by the device manufacturer.
You can play Saavn and other radio stations with the default clientID and clientSecret used by the app.
Let us know if you are looking to go to production and Amazon music is a required functionality.

**Comment by Yeremiy** [comment]
Hello ESPS32-LiraT radio Alex plays without problems, but does not want music. Govort: I can not play Amazon music on this device. I have clientID and clientSecret, what to do with them? Please tell me. Thank.
